upstream api { server api:8080; }
upstream admin { server platform-admin:8080; }
upstream clinic { server clinic-app:80; }
upstream public_app { server public-app:80; }

server {
    listen 80 default_server;
    server_name app.localhost;
    location /api/ { proxy_pass http://api; proxy_set_header X-Forwarded-Proto $scheme; proxy_set_header Host $host; }
    location / { proxy_pass http://clinic; }
}

server {
    listen 80;
    server_name api.localhost;
    location / { proxy_pass http://api; proxy_set_header X-Forwarded-Proto $scheme; proxy_set_header Host $host; }
}

server {
    listen 80;
    server_name admin.localhost;
    location / { proxy_pass http://admin; proxy_set_header X-Forwarded-Proto $scheme; proxy_set_header Host $host; }
}

server {
    listen 80;
    server_name book.localhost rx.localhost;
    location / { proxy_pass http://public_app; }
}
