import { CommonModule } from '@angular/common';
import { Component, inject, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { forkJoin, Observable } from 'rxjs';
import { LocalizationService } from '../../core/localization.service';
import { AuthService } from '../../core/auth.service';
import { PatientApiService, PatientListItem } from '../patients/patient-api.service';
import { TreatmentApiService, Treatment } from '../treatments/treatment-api.service';
import { Activity, Batch, BatchDetail, Claim, ClaimDetail, ClinicBusinessApi, ClinicDocument, InsuranceSummary, Payer, Policy } from './clinic-business-api.service';

@Component({
  selector: 'app-insurance-page',
  imports: [CommonModule, FormsModule],
  styleUrl: './clinic-business.scss',
  template: `
    <section class="business-page">
      <header class="business-head"><div><p class="eyebrow">CLINIC OPERATIONS</p><h1>{{ t('Insurance claims', 'التأمينات والمطالبات') }}</h1><p>{{ t('Private plans and universal health insurance, with individual or grouped settlements.', 'شركات التأمين الخاصة والتأمين الصحي الشامل، بمطالبات وتسويات منفردة أو مجمعة.') }}</p></div></header>
      @if (error) { <div class="business-alert error" role="alert">{{ error }}</div> }
      @if (notice) { <div class="business-alert success" role="status">{{ notice }}</div> }
      <div class="business-stats"><div><small>{{ t('Claims', 'المطالبات') }}</small><strong>{{ claims.length }}</strong></div><div><small>{{ t('Awaiting decision', 'بانتظار رد') }}</small><strong>{{ awaitingCount() }}</strong></div><div><small>{{ t('Rejected', 'مرفوض') }}</small><strong>{{ rejectedCount() }}</strong></div><div><small>{{ t('Outstanding from insurers', 'المستحق من الجهات') }}</small><strong>{{ summary?.outstanding == null ? '—' : (summary!.outstanding | number:'1.2-2') }}</strong><small>{{ summary?.currency || 'EGP' }}</small></div></div>
      <div class="business-card business-inline"><input [(ngModel)]="patientSearch" [placeholder]="t('Search patients by name or phone', 'ابحث عن مريض بالاسم أو الهاتف')" /><button class="business-primary" (click)="searchPatients()">{{ t('Search patients', 'بحث عن المرضى') }}</button></div>

      @if (auth.hasPermission('Insurance.Manage')) { <div class="business-grid">
        <section class="business-card"><h2>{{ t('Insurance provider', 'جهة التأمين') }}</h2><div class="business-fields"><label>{{ t('Name', 'اسم الجهة') }}<input [(ngModel)]="payerForm.name" /></label><label>{{ t('Type', 'النوع') }}<select [(ngModel)]="payerForm.kind"><option [ngValue]="1">{{ t('Private / TPA', 'شركة خاصة / إدارة مطالبات') }}</option><option [ngValue]="2">{{ t('Universal health insurance', 'التأمين الصحي الشامل') }}</option></select></label><label class="wide">{{ t('Clinic contract number', 'رقم عقد العيادة') }}<input [(ngModel)]="payerForm.contractNumber" /></label></div><button class="business-primary" [disabled]="busy || !payerForm.name.trim()" (click)="createPayer()">{{ t('Save provider', 'حفظ الجهة') }}</button></section>
        <section class="business-card"><h2>{{ t('Patient coverage', 'تأمين المريض') }}</h2><div class="business-fields"><label>{{ t('Patient', 'المريض') }}<select [(ngModel)]="policyForm.patientId"><option value="">{{ t('Select', 'اختر') }}</option>@for (p of patients; track p.id) { <option [value]="p.id">{{ p.fullName }}</option> }</select></label><label>{{ t('Provider', 'الجهة') }}<select [(ngModel)]="policyForm.payerId"><option value="">{{ t('Select', 'اختر') }}</option>@for (p of payers; track p.id) { <option [value]="p.id">{{ p.name }}</option> }</select></label><label>{{ t('Member number', 'رقم العضوية') }}<input [(ngModel)]="policyForm.memberNumber" /></label><label>{{ t('Expiry', 'تاريخ الانتهاء') }}<input type="date" [(ngModel)]="policyForm.expiresAt" /></label><label class="wide">{{ t('Referral number', 'رقم الإحالة إن وجد') }}<input [(ngModel)]="policyForm.referralNumber" /></label></div><button class="business-primary" [disabled]="busy || !policyForm.patientId || !policyForm.payerId || !policyForm.memberNumber" (click)="createPolicy()">{{ t('Save coverage', 'حفظ التأمين') }}</button></section>
      </div> }

      @if (auth.hasPermission('Insurance.Manage')) { <section class="business-card"><h2>{{ t('New claim', 'مطالبة جديدة') }}</h2><p>{{ t('The treatment remains in the patient record. This claim tracks the insurer’s decision and payment separately.', 'العلاج يفضل في ملف المريض؛ المطالبة هنا تتابع قرار الجهة ومبلغ السداد بشكل مستقل.') }}</p><div class="business-fields"><label>{{ t('Patient', 'المريض') }}<select [(ngModel)]="claimPatientId" (change)="onClaimPatient()"><option value="">{{ t('Select', 'اختر') }}</option>@for (p of patients; track p.id) { <option [value]="p.id">{{ p.fullName }}</option> }</select></label><label>{{ t('Policy', 'الوثيقة') }}<select [(ngModel)]="claimForm.patientInsuranceId"><option value="">{{ t('Select', 'اختر') }}</option>@for (p of patientPolicies(); track p.id) { <option [value]="p.id">{{ payerName(p.payerId) }} · {{ p.memberNumber }}</option> }</select></label><label>{{ t('Treatment', 'العلاج') }}<select [(ngModel)]="claimForm.treatmentId" (change)="setTreatmentAmount()"><option value="">{{ t('Select', 'اختر') }}</option>@for (tr of treatments; track tr.id) { <option [value]="tr.id">{{ tr.treatmentName }} · {{ tr.price | number:'1.2-2' }}</option> }</select></label><label>{{ t('Requested from insurer', 'المطلوب من الجهة') }}<input type="number" min="0" step="0.01" [(ngModel)]="claimForm.requestedAmount" /></label><label>{{ t('Expected patient share', 'المتوقع على المريض') }}<input type="number" min="0" step="0.01" [(ngModel)]="claimForm.patientShare" /></label><label class="wide">{{ t('Notes', 'ملاحظات') }}<input [(ngModel)]="claimForm.notes" /></label></div><button class="business-primary" [disabled]="busy || !claimForm.patientInsuranceId || !claimForm.treatmentId || claimForm.requestedAmount <= 0" (click)="createClaim()">{{ t('Create claim', 'إنشاء المطالبة') }}</button></section> }

      <section class="business-card"><div class="business-row"><div><h2>{{ t('Claims', 'المطالبات') }}</h2><p>{{ t('Select claims from one provider to make a batch, or settle a claim alone.', 'حدد مطالبات من جهة واحدة لعمل دفعة، أو سوّي مطالبة لوحدها.') }}</p></div><div class="business-inline"><select [(ngModel)]="batchPayerId" (change)="selectedClaims.clear()"><option value="">{{ t('All providers', 'كل الجهات') }}</option>@for (p of payers; track p.id) { <option [value]="p.id">{{ p.name }}</option> }</select><button class="business-primary" [disabled]="busy || !auth.hasPermission('Insurance.Manage') || selectedClaims.size === 0" (click)="createBatch()">{{ t('Create batch', 'إنشاء دفعة') }} ({{ selectedClaims.size }})</button></div></div><div class="business-table-wrap"><table><thead><tr><th></th><th>{{ t('Patient / provider', 'المريض / الجهة') }}</th><th>{{ t('Requested', 'المطلوب') }}</th><th>{{ t('Approved', 'المعتمد') }}</th><th>{{ t('Patient share', 'حصة المريض') }}</th><th>{{ t('Status', 'الحالة') }}</th><th>{{ t('Action', 'إجراء') }}</th></tr></thead><tbody>
        @for (c of visibleClaims(); track c.id) { <tr><td><input type="checkbox" [checked]="selectedClaims.has(c.id)" [disabled]="!auth.hasPermission('Insurance.Manage') || !!c.batchId || ![4,6,7].includes(c.status)" (change)="toggleClaim(c.id, $event)" /></td><td><strong>{{ patientName(c.patientId) }}</strong><small>{{ payerForClaim(c) }} · {{ treatmentName(c.treatmentId) }}</small></td><td>{{ c.requestedAmount | number:'1.2-2' }}</td><td>{{ c.approvedAmount == null ? '—' : (c.approvedAmount | number:'1.2-2') }}</td><td>{{ c.patientShare | number:'1.2-2' }}</td><td><span class="business-chip">{{ statusName(c.status) }}</span>@if (c.batchId) { <small>{{ t('In batch', 'داخل دفعة') }}</small> }</td><td><select [ngModel]="c.status" (ngModelChange)="setStatus(c, $event)" [disabled]="busy || !auth.hasPermission('Insurance.Manage') || c.status === 8 || c.status === 9"><option [ngValue]="c.status">{{ statusName(c.status) }}</option>@for (s of statuses; track s.id) { @if (s.id !== c.status) { <option [ngValue]="s.id">{{ t(s.en, s.ar) }}</option> } }</select><button class="business-link" (click)="showHistory(c)">{{ t('History', 'السجل') }}</button>@if (auth.hasPermission('Insurance.Settle') && !c.batchId && [4,6,7].includes(c.status) && c.approvedAmount != null) { <button class="business-link" (click)="openSingle(c)">{{ t('Settle', 'تسوية') }}</button> }</td></tr> }
        @if (visibleClaims().length === 0) { <tr><td colspan="7" class="business-empty">{{ t('No claims yet.', 'لا توجد مطالبات بعد.') }}</td></tr> }
      </tbody></table></div></section>

      @if (singleDetail) { <section class="business-card"><h2>{{ t('Individual settlement', 'تسوية مطالبة منفردة') }} · {{ patientName(singleDetail.claim.patientId) }}</h2><div class="business-summary"><span>{{ t('Approved / requested', 'المعتمد / المطلوب') }}: <strong>{{ (singleDetail.claim.approvedAmount ?? singleDetail.claim.requestedAmount) | number:'1.2-2' }}</strong></span><span>{{ t('Received', 'المستلم') }}: <strong>{{ singleDetail.paid | number:'1.2-2' }}</strong></span><span>{{ t('Remaining', 'المتبقي') }}: <strong>{{ singleDetail.outstanding | number:'1.2-2' }}</strong></span></div><div class="business-inline"><input type="number" min="0" [max]="singleDetail.outstanding" step="0.01" [(ngModel)]="singleAmount" [placeholder]="t('Amount received', 'المبلغ المستلم')" /><input [(ngModel)]="paymentReference" [placeholder]="t('Payment reference', 'مرجع الدفع')" /><button class="business-primary" [disabled]="busy || singleAmount <= 0 || singleAmount > singleDetail.outstanding" (click)="settleSingle()">{{ t('Record payment', 'تسجيل السداد') }}</button></div>@for (p of singleDetail.settlements; track p.id) { <p class="business-history">{{ p.amount | number:'1.2-2' }} · {{ p.paidAt | date:'dd/MM/yyyy' }} · {{ p.reference || '—' }}</p> }</section> }

      <section class="business-card"><h2>{{ t('Grouped batches', 'الدفعات المجمعة') }}</h2><div class="business-inline statement-tabs">@for (b of batches; track b.id) { <button [class.active]="detail?.batch?.id === b.id" (click)="openBatch(b.id)">{{ b.reference }} · {{ payerName(b.payerId) }}</button> }</div>@if (detail) { <div class="business-summary"><span>{{ t('Requested', 'المطلوب') }}: <strong>{{ detail.requested | number:'1.2-2' }}</strong></span><span>{{ t('Received', 'المستلم') }}: <strong>{{ detail.paid | number:'1.2-2' }}</strong></span></div><div class="business-table-wrap"><table><thead><tr><th>{{ t('Patient / treatment', 'المريض / العلاج') }}</th><th>{{ t('Status / patient share', 'الحالة / حصة المريض') }}</th><th>{{ t('Requested', 'المطلوب') }}</th><th>{{ t('Approved', 'المعتمد') }}</th><th>{{ t('Paid', 'المدفوع') }}</th><th>{{ t('Remaining', 'المتبقي') }}</th>@if (auth.hasPermission('Insurance.Settle')) { <th>{{ t('Receive now', 'استلام الآن') }}</th> }</tr></thead><tbody>@for (row of detail.claims; track row.claim.id) { <tr><td>{{ patientName(row.claim.patientId) }}<small>{{ treatmentName(row.claim.treatmentId) }}</small></td><td>{{ statusName(row.claim.status) }}<small>{{ row.claim.patientShare | number:'1.2-2' }}</small></td><td>{{ row.claim.requestedAmount | number:'1.2-2' }}</td><td>{{ row.claim.approvedAmount == null ? '—' : (row.claim.approvedAmount | number:'1.2-2') }}</td><td>{{ row.paid | number:'1.2-2' }}</td><td>{{ row.outstanding | number:'1.2-2' }}</td>@if (auth.hasPermission('Insurance.Settle')) { <td><input type="number" min="0" [max]="row.outstanding" step="0.01" [(ngModel)]="paymentAmounts[row.claim.id]" /></td> }</tr> }</tbody></table></div>@if (auth.hasPermission('Insurance.Settle')) { <div class="business-inline"><input [(ngModel)]="paymentReference" [placeholder]="t('Transfer reference', 'مرجع التحويل')" /><button class="business-primary" [disabled]="busy" (click)="settleBatch()">{{ t('Record settlement', 'تسجيل التسوية') }}</button></div> } }</section>
      @if (historyClaim) { <section class="business-card"><h2>{{ t('Claim history and documents', 'سجل المطالبة والمرفقات') }} · {{ patientName(historyClaim.patientId) }}</h2><div class="business-inline">@if (auth.hasPermission('Insurance.Manage')) { <input type="file" accept=".pdf,.jpg,.jpeg,.png" (change)="upload($event)" /> }<small>{{ t('PDF or image, up to 5 MB', 'PDF أو صورة، حتى 5 ميجابايت') }}</small></div><div class="business-inline">@for (doc of documents; track doc.id) { <button class="business-link" (click)="download(doc)">{{ doc.fileName }} ↓</button> }</div>@for (event of history; track event.id) { <p class="business-history"><strong>{{ event.action }}</strong> · {{ event.occurredAt | date:'dd/MM/yyyy HH:mm' }} · {{ event.actorName || '—' }} · {{ event.details || '' }}</p> }</section> }
    </section>
  `,
})
export class InsurancePageComponent implements OnInit {
  private readonly api = inject(ClinicBusinessApi); private readonly patientApi = inject(PatientApiService); private readonly treatmentApi = inject(TreatmentApiService); private readonly i18n = inject(LocalizationService); private readonly route = inject(ActivatedRoute); readonly auth = inject(AuthService);
  payers: Payer[] = []; policies: Policy[] = []; selectedPatientPolicies: Policy[] = []; claims: Claim[] = []; batches: Batch[] = []; patients: PatientListItem[] = []; treatments: Treatment[] = [];
  detail: BatchDetail | null = null; historyClaim: Claim | null = null; history: Activity[] = []; documents: ClinicDocument[] = []; singleDetail: ClaimDetail | null = null; singleAmount = 0;
  summary: InsuranceSummary | null = null;
  selectedClaims = new Set<string>(); batchPayerId = ''; paymentAmounts: Record<string, number> = {}; paymentReference = '';
  payerForm = { name: '', kind: 1, contractNumber: '' }; policyForm = { patientId: '', payerId: '', memberNumber: '', expiresAt: '', referralNumber: '' };
  claimPatientId = ''; claimForm = { patientInsuranceId: '', treatmentId: '', requestedAmount: 0, patientShare: 0, notes: '' };
  busy = false; error = ''; notice = '';
  filterPatientId = '';
  patientSearch = '';
  readonly statuses = [{ id: 2, en: 'Eligibility checked', ar: 'تم التحقق' }, { id: 3, en: 'Approval pending', ar: 'بانتظار الموافقة' }, { id: 4, en: 'Approved', ar: 'موافق عليه' }, { id: 5, en: 'Rejected', ar: 'مرفوض' }, { id: 6, en: 'Submitted', ar: 'اترسلت' }, { id: 7, en: 'Partially approved', ar: 'موافقة جزئية' }, { id: 9, en: 'Cancelled', ar: 'ملغي' }];
  ngOnInit() { this.filterPatientId = this.route.snapshot.queryParamMap.get('patientId') || ''; this.policyForm.patientId = this.filterPatientId; this.claimPatientId = this.filterPatientId; this.refresh(); this.patientApi.listAll().subscribe({ next: x => { this.patients = x; this.ensureSelectedPatient(); } }); if (this.filterPatientId) this.onClaimPatient(); }
  searchPatients() { this.patientApi.patients({ search: this.patientSearch, pageSize: 50 }).subscribe({ next: x => { this.patients = x.items; this.ensureSelectedPatient(); }, error: e => this.fail(e) }); }
  ensureSelectedPatient() { if (!this.filterPatientId || this.patients.some(x => x.id === this.filterPatientId)) return; this.patientApi.patient(this.filterPatientId).subscribe({ next: p => this.patients = [...this.patients, { id: p.id, patientNumber: p.patientNumber, fullName: [p.firstName, p.middleName, p.lastName].filter(Boolean).join(' '), gender: p.gender, phone: p.phone, email: p.email, status: p.status, createdAt: p.createdAt }] }); }
  t(en: string, ar: string) { return this.i18n.language() === 'ar' ? ar : en; }
  refresh() { forkJoin({ payers: this.api.payers(), policies: this.api.policies(this.filterPatientId || undefined), claims: this.api.claims(this.filterPatientId || undefined), batches: this.api.batches(), summary: this.api.insuranceSummary() }).subscribe({ next: x => { this.payers = x.payers; this.policies = x.policies; this.claims = x.claims; this.batches = x.batches; this.summary = x.summary; }, error: e => this.fail(e) }); }
  patientName(id: string) { return this.patients.find(x => x.id === id)?.fullName || id.slice(0, 8); }
  payerName(id: string) { return this.payers.find(x => x.id === id)?.name || id.slice(0, 8); }
  payerForClaim(c: Claim) { const p = this.policies.find(x => x.id === c.patientInsuranceId); return p ? this.payerName(p.payerId) : '—'; }
  treatmentName(id: string) { return this.treatments.find(x => x.id === id)?.treatmentName || id.slice(0, 8); }
  statusName(id: number) { return id === 1 ? this.t('Draft', 'مسودة') : id === 8 ? this.t('Settled', 'تمت التسوية') : this.statuses.find(x => x.id === id)?.[this.i18n.language() === 'ar' ? 'ar' : 'en'] || String(id); }
  awaitingCount() { return this.claims.filter(x => x.status === 3 || x.status === 6).length; }
  rejectedCount() { return this.claims.filter(x => x.status === 5).length; }
  patientPolicies() { return this.selectedPatientPolicies; }
  visibleClaims() { return this.claims.filter(x => !this.batchPayerId || this.policies.find(p => p.id === x.patientInsuranceId)?.payerId === this.batchPayerId); }
  onClaimPatient() { this.claimForm.patientInsuranceId = ''; this.claimForm.treatmentId = ''; if (!this.claimPatientId) { this.treatments = []; this.selectedPatientPolicies = []; return; } this.treatmentApi.treatments({ patientId: this.claimPatientId, pageSize: '100' }).subscribe({ next: x => this.treatments = x.items }); this.api.policies(this.claimPatientId).subscribe({ next: x => this.selectedPatientPolicies = x, error: e => this.fail(e) }); }
  setTreatmentAmount() { const tr = this.treatments.find(x => x.id === this.claimForm.treatmentId); if (tr) this.claimForm.requestedAmount = tr.price; }
  toggleClaim(id: string, event: Event) { const checked = (event.target as HTMLInputElement).checked; if (checked) { const claim = this.claims.find(x => x.id === id); const payer = claim && this.policies.find(x => x.id === claim.patientInsuranceId)?.payerId; if (payer && payer === this.batchPayerId) this.selectedClaims.add(id); else { (event.target as HTMLInputElement).checked = false; this.error = this.t('Choose a provider first.', 'اختار جهة التأمين الأول.'); } } else this.selectedClaims.delete(id); }
  private save(action: Observable<unknown>, message: string, after?: () => void) { this.busy = true; this.error = ''; this.notice = ''; action.subscribe({ next: () => { this.busy = false; this.notice = message; after?.(); this.refresh(); }, error: e => { this.busy = false; this.fail(e); } }); }
  private fail(e: { error?: { detail?: string } }) { this.error = e?.error?.detail || this.t('Could not save. Please review the details.', 'تعذر الحفظ، راجع البيانات وحاول تاني.'); }
  createPayer() { this.save(this.api.addPayer(this.payerForm), this.t('Provider saved.', 'تم حفظ الجهة.'), () => this.payerForm = { name: '', kind: 1, contractNumber: '' }); }
  createPolicy() { const patientId = this.policyForm.patientId; this.save(this.api.addPolicy({ ...this.policyForm, expiresAt: this.policyForm.expiresAt ? new Date(this.policyForm.expiresAt + 'T23:59:59').toISOString() : null }), this.t('Coverage saved.', 'تم حفظ تأمين المريض.'), () => { this.policyForm = { patientId: '', payerId: '', memberNumber: '', expiresAt: '', referralNumber: '' }; if (this.claimPatientId === patientId) this.onClaimPatient(); }); }
  createClaim() { this.save(this.api.addClaim(this.claimForm), this.t('Claim created.', 'تم إنشاء المطالبة.'), () => this.claimForm = { patientInsuranceId: '', treatmentId: '', requestedAmount: 0, patientShare: 0, notes: '' }); }
  setStatus(claim: Claim, status: number) { if (status === claim.status) return; const amountText = status === 4 || status === 7 ? window.prompt(this.t('Approved insurer amount', 'المبلغ المعتمد من الجهة'), String(claim.approvedAmount ?? claim.requestedAmount)) : null; if ((status === 4 || status === 7) && amountText === null) return; const approvedAmount = amountText === null ? claim.approvedAmount ?? null : Number(amountText); const approvalNumber = status === 4 || status === 7 ? window.prompt(this.t('Approval number (optional)', 'رقم الموافقة (اختياري)')) : claim.approvalNumber; const notes = window.prompt(this.t('Decision note / rejection reason', 'ملاحظة القرار أو سبب الرفض')) || claim.notes; this.save(this.api.claimStatus(claim.id, { status, approvedAmount, approvalNumber, externalClaimNumber: claim.externalClaimNumber, notes }), this.t('Claim updated.', 'تم تحديث المطالبة.')); }
  createBatch() { if (!this.batchPayerId) { this.error = this.t('Choose a provider first.', 'اختار جهة التأمين الأول.'); return; } this.save(this.api.addBatch(this.batchPayerId, [...this.selectedClaims]), this.t('Batch created.', 'تم إنشاء الدفعة.'), () => this.selectedClaims.clear()); }
  openBatch(id: string) { this.api.batch(id).subscribe({ next: x => { this.detail = x; this.paymentAmounts = {}; }, error: e => this.fail(e) }); }
  openSingle(c: Claim) { this.singleAmount = 0; this.detail = null; this.api.claim(c.id).subscribe({ next: x => this.singleDetail = x, error: e => this.fail(e) }); }
  settleSingle() { if (!this.singleDetail) return; this.save(this.api.settleClaims(null, [{ itemId: this.singleDetail.claim.id, amount: Number(this.singleAmount) }], this.paymentReference), this.t('Payment recorded.', 'تم تسجيل السداد.'), () => { this.singleDetail = null; this.paymentReference = ''; }); }
  settleBatch() { if (!this.detail) return; const allocations = this.detail.claims.map(x => ({ itemId: x.claim.id, amount: Number(this.paymentAmounts[x.claim.id] || 0) })).filter(x => x.amount > 0); if (!allocations.length) { this.error = this.t('Enter at least one received amount.', 'اكتب مبلغ مستلم واحد على الأقل.'); return; } const id = this.detail.batch.id; this.save(this.api.settleClaims(id, allocations, this.paymentReference), this.t('Settlement recorded.', 'تم تسجيل التسوية.'), () => { this.paymentReference = ''; this.openBatch(id); }); }
  showHistory(c: Claim) { this.historyClaim = c; this.api.claimHistory(c.id).subscribe({ next: x => this.history = x }); this.api.claimDocuments(c.id).subscribe({ next: x => this.documents = x }); }
  upload(event: Event) { const file = (event.target as HTMLInputElement).files?.[0]; if (!file || !this.historyClaim) return; const id = this.historyClaim.id; this.save(this.api.uploadClaimDocument(id, file), this.t('Document added.', 'تمت إضافة المرفق.'), () => this.showHistory(this.historyClaim!)); (event.target as HTMLInputElement).value = ''; }
  download(doc: ClinicDocument) { this.api.downloadClaimDocument(doc.id).subscribe({ next: blob => { const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = doc.fileName; a.click(); URL.revokeObjectURL(url); }, error: e => this.fail(e) }); }
}
