namespace DentalClinic.Domain.Platform;

public enum PlatformAuditAction
{
    TenantCreated = 1,
    TenantUpdated = 2,
    TenantActivated = 3,
    TenantDeactivated = 4,
    TenantSuspended = 5,
    AdminInvitationCreated = 6,
    AdminInvitationAccepted = 7,
    UserInvited = 8,
    InvitationAccepted = 9,
    UserActivated = 10,
    UserDeactivated = 11,
    RoleAssigned = 12,
    RoleRemoved = 13,
    RoleCreated = 14,
    RoleUpdated = 15,
    PermissionsChanged = 16,
    PatientCreated = 17,
    PatientUpdated = 18,
    PatientArchived = 19,
    MedicalConditionAdded = 20,
    MedicalConditionUpdated = 21,
    MedicalConditionRemoved = 22,
    AllergyAdded = 23,
    AllergyUpdated = 24,
    AllergyRemoved = 25,
    MedicationAdded = 26,
    MedicationUpdated = 27,
    MedicationRemoved = 28,
    SurgeryAdded = 29,
    SurgeryUpdated = 30,
    SurgeryRemoved = 31,
    DoctorProfileCreated = 32,
    DoctorProfileUpdated = 33,
    DoctorProfileActivated = 34,
    DoctorProfileDeactivated = 35,
    DoctorProfileArchived = 36,
    DoctorScheduleCreated = 37,
    DoctorScheduleUpdated = 38,
    DoctorCompensationCreated = 39,
    DoctorCompensationUpdated = 40
}
